### ISSUE TITLE
Question - are you interesting by contributing ?

### ISSUE THREAD

**Issue by laudeco** [ATM-Consulting/dolibarr_module_visitemedicale#1]
Hello, 

I'll work on it, since I need it and that's not completely a working code (mainly on the latest version of Dolibarr 5.0), I will work on it.

I already forked your work.

Are you interesting by contributing, I follow some rules :
* I'll not hardcoded my values => always working by dictionaries
* I don't touch code if I don't need it

Kind regards
Laurent

**Comment by atm-alexis** [comment]
Hi Laurent,

No problem, we would be glad to receive your contributions ;)

Regards,
Alexis
